# Generated by Django 4.0.3 on 2022-03-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_name', models.CharField(blank=True, max_length=50, null=True)),
                ('i_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('w_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_id', models.IntegerField()),
                ('s_qty', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stocks',
                'managed': True,
                'unique_together': {('w_id', 'i_id')},
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('w_id', models.IntegerField(primary_key=True, serialize=False)),
                ('w_name', models.CharField(blank=True, max_length=50, null=True)),
                ('w_street_1', models.CharField(blank=True, max_length=50, null=True)),
                ('w_street_2', models.CharField(blank=True, max_length=50, null=True)),
                ('w_city', models.CharField(blank=True, max_length=50, null=True)),
                ('w_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'warehouses',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
